### ISSUE TITLE
"Stream is not readable" on reboot

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1420]
### Describe the bug:

1. Visit http://localhost:3000/dashboard/chapters/1
2. Reload server
3. Reload page
4. See "InternalServerError: stream is not readable" in server console logs
5. Reload page
6. No error

It's a bit mystifying, particularly since there's no obvious side effects of this beside the error appearing in the logs.

### Tell us about your browser and operating system:
- Browser(s) name and version: Chrome 103.0.5060.134 and Brave  v1.42.97
- Operating System: Ubuntu

**Comment by gikf** [comment]
I can confirm this occurring also ie. in `dashboard/venues/{id}`, `dashboard/sponsors/{id}`. I wasn't getting it on `dashboard/events/{id}`.

**Comment by gikf** [comment]
It appears that sometimes the initial query with the `id` of `-1` gets aborted (or simply errors) due to `ECONNRESET`

```
"Error: aborted
    at connResetException (node:internal/errors:691:14)
    at abortIncoming (node:_http_server:596:17)
    at socketOnClose (node:_http_server:590:3)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"
```

This is consistent across multiple mentioned pages. With __readableState_ of the `req` being for example:

<details><summary>_readableState</summary>

```
{
  objectMode: false,
  highWaterMark: 16384,
  buffer: {
    head: {
      data: new Uint8Array([123, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 78, 97, 109, 101, 34, 58, 34, 115, 112, 111, 110, 115, 111, 114, 34, 44, 34, 118, 97, 114, 105, 97, 98, 108, 101, 115, 34, 58, 123, 34, 115, 112, 111, 110, 115, 111, 114, 73, 100, 34, 58, 45, 49, 125, 44, 34, 113, 117, 101, 114, 121, 34, 58, 34, 113, 117, 101, 114, 121, 32, 115, 112, 111, 110, 115, 111, 114, 40, 36, 115, 112, 111, 110, 115, 111, 114, 73, 100, 58, 32, 73, 110, 116, 33, 41, 32, 123, 92, 110, 32, 32, 115, 112, 111, 110, 115, 111, 114, 40, 105, 100, 58, 32, 36, 115, 112, 111, 110, 115, 111, 114, 73, 100, 41, 32, 123, 92, 110, 32, 32, 32, 32, 105, 100, 92, 110, 32, 32, 32, 32, 110, 97, 109, 101, 92, 110, 32, 32, 32, 32, 119, 101, 98, 115, 105, 116, 101, 92, 110, 32, 32, 32, 32, 108, 111, 103, 111, 95, 112, 97, 116, 104, 92, 110, 32, 32, 32, 32, 116, 121, 112, 101, 92, 110, 32, 32, 32, 32, 95, 95, 116, 121, 112, 101, 110, 97, 109, 101, 92, 110, 32, 32, 125, 92, 110, 125, 92, 110, 34, 125]),
      next: null,
    },
    tail: {
      data: new Uint8Array([123, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 78, 97, 109, 101, 34, 58, 34, 115, 112, 111, 110, 115, 111, 114, 34, 44, 34, 118, 97, 114, 105, 97, 98, 108, 101, 115, 34, 58, 123, 34, 115, 112, 111, 110, 115, 111, 114, 73, 100, 34, 58, 45, 49, 125, 44, 34, 113, 117, 101, 114, 121, 34, 58, 34, 113, 117, 101, 114, 121, 32, 115, 112, 111, 110, 115, 111, 114, 40, 36, 115, 112, 111, 110, 115, 111, 114, 73, 100, 58, 32, 73, 110, 116, 33, 41, 32, 123, 92, 110, 32, 32, 115, 112, 111, 110, 115, 111, 114, 40, 105, 100, 58, 32, 36, 115, 112, 111, 110, 115, 111, 114, 73, 100, 41, 32, 123, 92, 110, 32, 32, 32, 32, 105, 100, 92, 110, 32, 32, 32, 32, 110, 97, 109, 101, 92, 110, 32, 32, 32, 32, 119, 101, 98, 115, 105, 116, 101, 92, 110, 32, 32, 32, 32, 108, 111, 103, 111, 95, 112, 97, 116, 104, 92, 110, 32, 32, 32, 32, 116, 121, 112, 101, 92, 110, 32, 32, 32, 32, 95, 95, 116, 121, 112, 101, 110, 97, 109, 101, 92, 110, 32, 32, 125, 92, 110, 125, 92, 110, 34, 125]),
      next: null,
    },
    length: 1,
  },
  length: 211,
  pipes: [
  ],
  flowing: null,
  ended: true,
  endEmitted: false,
  reading: false,
  constructed: true,
  sync: true,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: true,
  autoDestroy: true,
  destroyed: true,
  errored: {
    code: "ECONNRESET",
  },
  closed: true,
  closeEmitted: true,
  defaultEncoding: "utf8",
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: true,
  dataEmitted: false,
  decoder: null,
  encoding: null,
}
```
</details>

The decoded data:
```
{
  operationName: 'sponsor',
  variables: { sponsorId: -1 },
  query: 'query sponsor($sponsorId: Int!) {\n' +
    '  sponsor(id: $sponsorId) {\n' +
    '    id\n' +
    '    name\n' +
    '    website\n' +
    '    logo_path\n' +
    '    type\n' +
    '    __typename\n' +
    '  }\n' +
    '}\n'
}
```

**Comment by ojeytonwilliams** [comment]
Nice debugging work. Silly question, probably, but how are you getting those logs?  

This does look like it's the problem.  The apollo client must be dropping the connection part way through.

**Comment by gikf** [comment]
Probably not silly, it was quite fun. I was starting server in the _JavaScript Debug Terminal_ in VS Code, with breakpoint set lower and lower of the server error stack: <details>
```
[1] InternalServerError: stream is not readable
[1]     at readStream (/chapter/node_modules/raw-body/index.js:178:17)
[1]     at getRawBody (/chapter/node_modules/raw-body/index.js:109:12)
[1]     at read (/chapter/node_modules/body-parser/lib/read.js:79:3)
[1]     at jsonParser (/chapter/node_modules/body-parser/lib/types/json.js:135:5)
[1]     at Layer.handle [as handle_request] (/chapter/node_modules/express/lib/router/layer.js:95:5)
[1]     at trim_prefix (/chapter/node_modules/express/lib/router/index.js:328:13)
[1]     at /chapter/node_modules/express/lib/router/index.js:286:9
[1]     at Function.process_params (/chapter/node_modules/express/lib/router/index.js:346:12)
[1]     at next (/chapter/node_modules/express/lib/router/index.js:280:10)
[1]     at cors (/chapter/node_modules/cors/lib/index.js:188:7)
```
</details>

and then examining the `req` object in the _Closure (handle)_ :eyes:.

I got from the top to the `/chapter/node_modules/express/lib/router/index.js`. There were some other properties that I looked at in the meantime, but in the end, the error happens when `req.aborted` is `true` (thankfully breakpoint can be modified to be triggered conditionally). That will also mean the `req.readable` is `false`.

Error log from previous comment is from `req._readableState.errored.stack` in the VS Code's _Variables_ bar.

**Comment by ojeytonwilliams** [comment]
Nice, that makes a ton of sense.  Thanks for the walkthrough :)

Once I stopped the client from sending the requests with id = -1 (which, tbh, I should have done even without this bug), I've not been able to reproduce the error. I'm pretty sure this was the only issue.
